//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoLibrary.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class aqtraydata
    {
        public int TrayId { get; set; }
        public string Date { get; set; }
        public string TimeStart { get; set; }
        public string TimeEnd { get; set; }
        public string UsedTime { get; set; }
        public string TesterNumber { get; set; }
        public string Customer { get; set; }
        public string Product { get; set; }
        public string User { get; set; }
        public string LotNumber { get; set; }
        public string DocControl1 { get; set; }
        public string DocControl2 { get; set; }
        public string Sus { get; set; }
        public string AssyLine { get; set; }
    
        public virtual tray tray { get; set; }
    }
}
