//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoLibrary.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class hgainfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hgainfo()
        {
            this.hgainfoViews = new HashSet<hgainfoView>();
        }
    
        public int Id { get; set; }
        public string LineNo { get; set; }
        public Nullable<int> PalletId { get; set; }
        public int Position { get; set; }
        public System.DateTime Processdatetime { get; set; }
        public string IaviResult { get; set; }
        public int VmiResult { get; set; }
        public string SerialNumber { get; set; }
        public string IaviSerialNumber { get; set; }
        public Nullable<int> TrayId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public double A_Location { get; set; }
        public double B_Location { get; set; }
        public double Skew { get; set; }
        public double PitchOffset { get; set; }
        public double RollOffset { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hgainfoView> hgainfoViews { get; set; }
        public virtual pallet pallet { get; set; }
    }
}
