//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARB_Host.MITECSWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MITECSWebService.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLotNumbers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLotNumbers(string LINE_NO, string MODULECONTROLLER_MAC, string API_KEY, ref string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLotListDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLotListDetails(string lotNumberXML, ref string retMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLotNumbersByLinePartNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLotNumbersByLinePartNo(string LINE_NO, string PART_NUMBER, string MODULECONTROLLER_MAC, string API_KEY, ref string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registerLine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool registerLine(string LINE_NO, string MODULECONTROLLER_MAC, string API_KEY, ref string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateLotNumMovement", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool updateLotNumMovement(string LINE_NO, string MODULECONTROLLER_MAC, string API_KEY, string xmlDoc, ref string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cryptoLineRegistration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string cryptoLineRegistration(string LINE_NO, string MODULECONTROLLER_MAC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWebServiceVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getWebServiceVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartNumberDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPartNumberDetail(string hostLineNum, string hostMAC, string hostAPIKey, string PartNumberType, string PartNumber, ref string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLotDataByWaferCriteria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLotDataByWaferCriteria(string WaferNumber, string SbrNumber, string PartNumber, ref string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMaterLotsetup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMaterLotsetup(string Value, string LotSetupFilterType, ref string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : ARB_Host.MITECSWebService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ARB_Host.MITECSWebService.ServiceSoap>, ARB_Host.MITECSWebService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetLotNumbers(string LINE_NO, string MODULECONTROLLER_MAC, string API_KEY, ref string msg) {
            return base.Channel.GetLotNumbers(LINE_NO, MODULECONTROLLER_MAC, API_KEY, ref msg);
        }
        
        public System.Data.DataSet GetLotListDetails(string lotNumberXML, ref string retMsg) {
            return base.Channel.GetLotListDetails(lotNumberXML, ref retMsg);
        }
        
        public System.Data.DataSet GetLotNumbersByLinePartNo(string LINE_NO, string PART_NUMBER, string MODULECONTROLLER_MAC, string API_KEY, ref string msg) {
            return base.Channel.GetLotNumbersByLinePartNo(LINE_NO, PART_NUMBER, MODULECONTROLLER_MAC, API_KEY, ref msg);
        }
        
        public bool registerLine(string LINE_NO, string MODULECONTROLLER_MAC, string API_KEY, ref string msg) {
            return base.Channel.registerLine(LINE_NO, MODULECONTROLLER_MAC, API_KEY, ref msg);
        }
        
        public bool updateLotNumMovement(string LINE_NO, string MODULECONTROLLER_MAC, string API_KEY, string xmlDoc, ref string msg) {
            return base.Channel.updateLotNumMovement(LINE_NO, MODULECONTROLLER_MAC, API_KEY, xmlDoc, ref msg);
        }
        
        public string cryptoLineRegistration(string LINE_NO, string MODULECONTROLLER_MAC) {
            return base.Channel.cryptoLineRegistration(LINE_NO, MODULECONTROLLER_MAC);
        }
        
        public string getWebServiceVersion() {
            return base.Channel.getWebServiceVersion();
        }
        
        public System.Data.DataSet GetPartNumberDetail(string hostLineNum, string hostMAC, string hostAPIKey, string PartNumberType, string PartNumber, ref string msg) {
            return base.Channel.GetPartNumberDetail(hostLineNum, hostMAC, hostAPIKey, PartNumberType, PartNumber, ref msg);
        }
        
        public System.Data.DataSet GetLotDataByWaferCriteria(string WaferNumber, string SbrNumber, string PartNumber, ref string msg) {
            return base.Channel.GetLotDataByWaferCriteria(WaferNumber, SbrNumber, PartNumber, ref msg);
        }
        
        public System.Data.DataSet GetMaterLotsetup(string Value, string LotSetupFilterType, ref string msg) {
            return base.Channel.GetMaterLotsetup(Value, LotSetupFilterType, ref msg);
        }
    }
}
