//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoLibrary.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class pallet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pallet()
        {
            this.hgainfoes = new HashSet<hgainfo>();
        }
    
        public int Id { get; set; }
        public string PalletSN { get; set; }
        public Nullable<int> PalletOrder { get; set; }
        public Nullable<int> TrayId { get; set; }
        public System.DateTime Processdatetime { get; set; }
        public Nullable<int> ProcessPalletId { get; set; }
        public int IsCompleted { get; set; }
        public string PalletPath { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string Product { get; set; }
        public string LotNumber { get; set; }
        public string DocControl1 { get; set; }
        public string DocControl2 { get; set; }
        public string Sus { get; set; }
        public string AssyLine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hgainfo> hgainfoes { get; set; }
        public virtual tray tray { get; set; }
    }
}
