//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnOCR2040.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnOCR2040.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap GreenLED {
            get {
                object obj = ResourceManager.GetObject("GreenLED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenLEDs {
            get {
                object obj = ResourceManager.GetObject("GreenLEDs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HGA01 {
            get {
                object obj = ResourceManager.GetObject("HGA01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HGA02 {
            get {
                object obj = ResourceManager.GetObject("HGA02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HGA03 {
            get {
                object obj = ResourceManager.GetObject("HGA03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HGA04 {
            get {
                object obj = ResourceManager.GetObject("HGA04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HGA04ds {
            get {
                object obj = ResourceManager.GetObject("HGA04ds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HGA04s {
            get {
                object obj = ResourceManager.GetObject("HGA04s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hgst01 {
            get {
                object obj = ResourceManager.GetObject("hgst01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hgst01s {
            get {
                object obj = ResourceManager.GetObject("hgst01s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hgst02 {
            get {
                object obj = ResourceManager.GetObject("hgst02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hgst02s {
            get {
                object obj = ResourceManager.GetObject("hgst02s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hgst03 {
            get {
                object obj = ResourceManager.GetObject("hgst03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hgst03s {
            get {
                object obj = ResourceManager.GetObject("hgst03s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hgst04 {
            get {
                object obj = ResourceManager.GetObject("hgst04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hgst04s {
            get {
                object obj = ResourceManager.GetObject("hgst04s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hgst05s {
            get {
                object obj = ResourceManager.GetObject("hgst05s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hgst06s {
            get {
                object obj = ResourceManager.GetObject("hgst06s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hgst07s {
            get {
                object obj = ResourceManager.GetObject("hgst07s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HGSTTray {
            get {
                object obj = ResourceManager.GetObject("HGSTTray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HGSTTrayS {
            get {
                object obj = ResourceManager.GetObject("HGSTTrayS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HGSTTrayS2 {
            get {
                object obj = ResourceManager.GetObject("HGSTTrayS2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nozzle {
            get {
                object obj = ResourceManager.GetObject("nozzle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nozzle_ext1 {
            get {
                object obj = ResourceManager.GetObject("nozzle_ext1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nozzle_ret1 {
            get {
                object obj = ResourceManager.GetObject("nozzle_ret1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pbaX {
            get {
                object obj = ResourceManager.GetObject("pbaX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pbaX2 {
            get {
                object obj = ResourceManager.GetObject("pbaX2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedLED {
            get {
                object obj = ResourceManager.GetObject("RedLED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedLEDs {
            get {
                object obj = ResourceManager.GetObject("RedLEDs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WDTray {
            get {
                object obj = ResourceManager.GetObject("WDTray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WDTrayDS3 {
            get {
                object obj = ResourceManager.GetObject("WDTrayDS3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WDTrayFlipDL {
            get {
                object obj = ResourceManager.GetObject("WDTrayFlipDL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WDTrayFlipDR {
            get {
                object obj = ResourceManager.GetObject("WDTrayFlipDR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WDTrayFlipDS3 {
            get {
                object obj = ResourceManager.GetObject("WDTrayFlipDS3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WDTrayFlipL {
            get {
                object obj = ResourceManager.GetObject("WDTrayFlipL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WDTrayFlipR {
            get {
                object obj = ResourceManager.GetObject("WDTrayFlipR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WDTrayFlipS2 {
            get {
                object obj = ResourceManager.GetObject("WDTrayFlipS2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WDTrayS {
            get {
                object obj = ResourceManager.GetObject("WDTrayS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WDTrayS2 {
            get {
                object obj = ResourceManager.GetObject("WDTrayS2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
